CXX = g++
CPPFLAGS = -g -Wall -std=c++11

TARGETS = test_Array \
			test_FixLenStr \
			test_ObjTimer \
			test_ObjFuncInvoker \
			test_FixLenRankList \
			test_timeutil

all: $(TARGETS)

clean:
	-rm -f $(TARGETS)
